public class ThirdPartyErrorMsgConstants {
    public static final String COMMUNITY_USER_ID_MSG = 'The Representative communityUserID was not found or is incorrect.';
    public static final String POW_PIECE_RATE_START_DATE_ERROR_MSG = 'Start date of piece rate is invalid.';
    public static final String POW_PIECE_RATE_END_DATE_ERROR_MSG = 'End date of piece rate is invalid.';
    public static final String POW_SALARY_HOURLY_RATE_START_DATE_ERROR_MSG = 'Start date of salary rate is invalid.';
    public static final String POW_SALARY_HOURLY_RATE_END_DATE_ERROR_MSG = 'End date of salary rate is invalid.';
    public static final String POW_DIFFER_HOURLY_RATE_START_DATE_ERROR_MSG = 'Start date of different hourly rate is invalid.';
    public static final String POW_DIFFER_HOURLY_RATE_END_DATE_ERROR_MSG = 'End date of different hourly rate is invalid.';
    public static final String POW_HOURLY_RATE_START_DATE_ERROR_MSG = 'Start date of hourly rate is invalid.';
    public static final String POW_HOURLY_RATE_END_DATE_ERROR_MSG = 'End date of hourly rate is invalid.';
    public static final String LABEL_START_DATE_ERROR_MSG = 'Label start date is invalid.';
    public static final String LABEL_END_DATE_ERROR_MSG = 'Label end date is invalid.';
    public static final String HIRE_DATE_ERROR_MSG = 'Date of hire is invalid.';
    public static final String EMPLOYEMENT_QUIT_DATE_ERROR_MSG = 'Employement quit date is invalid.';
    public static final String EMPLOYEMENT_DISHCHARGED_DATE_ERROR_MSG = 'Employement discharged date is invalid.';
    public static final String EMPLOYER_INVALID_START_DATE_ERROR_MSG = 'Employer start date is invalid.';
    public static final String EMPLOYER_INVALID_END_DATE_ERROR_MSG = 'Employer end date is invalid.';
    public static final String CLAIMANT_INVALID_BIRTHDATE_ERROR_MSG = 'Claimant date of birth is invalid.';
    public static final String EMPLOYER_INVALID_COMPLAINED_DATE_ERROR_MSG = 'Retaliation filed complaint date is invalid.';
    public static final String INDUSTRY_INVALID_WRITTEN_DATE_ERROR_MSG = 'Date of written request is invalid.';
    public static final String INDUSTRY_INVALID_STATEMENT_DATE_ERROR_MSG = 'Employer statement date is invalid.';
    public static final String CLAIM_SUBMITTER_ERROR_MSG = 'Claim Submitter is missing.';
    public static final String ADVOCATE_TYPE_ERROR_MSG = 'Representative advocate type is missing.';
    public static final String BUSINESS_OR_ATTORNEY_NAME_ERROR_MSG = 'Business Name or Attorney Name/Representative Name is missing.';
    public static final String OTHERLOCATION_WORKADDRESS_REQUIRED_MSG = 'Work address is required.';
    public static final String OTHERLOCATION_ZIPCODE_REQUIRED_MSG = 'Work address zipcode is required.';
    public static final String OTHERLOCATION_ZIPCODE_ERROR_MSG = 'Work address zipcode must be 5 or 9 digits.';
    public static final String ADVOCATE_ZIPCODE_ERROR_MSG = 'Advocate zipcode must be 5 or 9 digits.';
    public static final String ADVOCATE_PHONE_NUMBER_ERROR_MSG = 'Advocate Phone number format is not match.';
    public static final String ADVOCATE_EMAIL_ERROR_MSG = 'Advocate email format is not correct.';
    public static final String ADVOCATE_WEBSITE_ERROR_MSG = 'Advocate website format is not correct.';
    public static final String CLAIMANT_FIRST_NAME_ERROR_MSG = 'Claimant first name is missing.';
    public static final String CLAIMANT_LAST_NAME_ERROR_MSG = 'Claimant Last Name is missing.';
    public static final String CLAIMANT_BIRTHDATE_REQ_ERROR_MSG = 'Claimant birthdate is missing.';
    public static final String CLAIMANT_BIRTHDATE_ERROR_MSG = 'Claimant birthdate must be smaller than today date.';
    public static final String CLAIMANT_ZIPCODE_REQ_ERROR_MSG = 'Claimant zipcode is missing.';
    public static final String CLAIMANT_ZIPCODE_ERROR_MSG = 'Claimant zipcode must be 5 or 9 digits.';
    public static final String CLAIMANT_CELL_PHONE_ERROR_MSG = 'Claimant cell phone format is not match.';
    public static final String CLAIMANT_HOME_PHONE_ERROR_MSG = 'Claimant home phone format is not match.';
    public static final String CLAIMANT_EMAIL_ERROR_MSG = 'Claimant email format is not match.';
    public static final String CLAIMANT_OTHER_PREFFERED_ERROR_MSG = 'Other Preferred language is missing.';
    public static final String EMPLOYER_TYPE_ERROR_MSG = 'Individual/Employer type is missing.';
    public static final String EMPLOYER_FIRST_NAME_ERROR_MSG = 'Employer first name is missing.';
    public static final String EMPLOYER_LAST_NAME_ERROR_MSG = 'Employer last name is missing.';
    public static final String EMPLOYER_STREET_ADDRESS_ERROR_MSG = 'Employer street address is missing.';
    public static final String EMPLOYER_CITY_ERROR_MSG = 'Employer city is missing.';
    public static final String EMPLOYER_STATE_ERROR_MSG = 'Employer state is missing.';
    public static final String EMPLOYER_ZIPCODE_REQ_ERROR_MSG = 'Employer zipcode is missing.';
    public static final String EMPLOYER_ZIPCODE_ERROR_MSG = 'Employer zipcode must be 5 or 9 digits.';
    public static final String EMPLOYER_BUSINESS_PHONE_ERROR_REQ_MSG = 'Employer business phone is missing.';
    public static final String EMPLOYER_BUSINESS_PHONE_ERROR_MSG = 'Employer business phone format is not match.';
    public static final String EMPLOYER_CELL_PHONE_REQ_ERROR_MSG = 'Employer cell phone is missing.';
    public static final String EMPLOYER_CELL_PHONE_ERROR_MSG = 'Employer cell phone format is not match.';
    public static final String EMPLOYER_EMAIL_ERROR_MSG = 'Employer email format is not correct.';
    public static final String EMPLOYER_WEBSITE_ERROR_MSG = 'Employer website format is not correct.';
    public static final String EMPLOYER_NO_OF_EMPLOYEES_ERROR_MSG = 'Invalid input in number of employees fields.';
    public static final String EMPLOYER_NO_OF_EMPLOYEES_REQ_ERROR_MSG = 'Number of employees is missing.';
    public static final String EMPLOYER_BUSINESS_NAME_ERROR_MSG = 'Employer business name is missing.';
    public static final String EMPLOYER_EXPLANATION_ERROR_MSG = 'Employer explanation is missing.';
    public static final String EMPLOYER_UNION_COVER_ERROR_MSG = 'Employer Union Cover is Missing';
    public static final String EMPLOYER_UNION_ADDRESS_ERROR_MSG = 'Employer union contract url address is missing.';
    public static final String EMPLOYER_UNION_OFFICE_LOCATOR_ERROR_MSG = 'Employer union office locator is missing.';
    public static final String EMPLOYER_COVID_19_ERROR_MSG = 'Covid-19 field is missing.';
    public static final String ATTACHMENT_ID_MISSING_ERROR_MSG = 'Attachment plus id is missing.';
    public static final String FILE_NAME_MISSING_ERROR_MSG = 'File name is missing.';
    public static final String VERSION_DATA_MISSING_ERROR_MSG = 'Content version data is missing.';
    public static final String EMPLOYER_OTHER_COVID_19_ERROR_MSG = 'Covid-19 other reason is missing.';
    
    public static String contentDataErrorMsg(String aPlusId){
        return 'No record found with this ' + aPlusId + ' Id.';
    }
    public static String caseNumberErrorMsg(String caseNumber){
        return 'Case number ' + caseNumber + ' not found.';
    }
    public static String claimantLastNameErrorMsg(String caseNumber, String claimantLastName){
        return 'Claimant Last Name ' + claimantLastName +' not found for Claim Number ' + caseNumber + '.';
    }
    public static String meetingsAndHearingMsg(String caseNumber){
        return 'No Meetings or Hearings found for Claim Number ' + caseNumber;
    }
}